### ISSUE TITLE
img src attr ignored if not prefixed with http(s)?

### ISSUE THREAD

**Issue by iku000888** [gitbucket/markedj#22]
Sorry if this is a known issue.

## Observed

```clojure
(import io.github.gitbucket.markedj.Marked)

(Marked/marked "![alt text](/img/some-image.png \"title\")")
=>
"<p><img alt=\"alt text\" title=\"title\"></p>"
```

## Expected (as in how markedjs behaves)

```clojure
(import io.github.gitbucket.markedj.Marked)

(Marked/marked "![alt text](/img/some-image.png \"title\")")
=>
"<p><img src=img/some-image.png alt=\"alt text\" title=\"title\"></p>"
```

**Comment by takezoe** [comment]
Markedj uses a whitelist for HTML rendering and it removes src attribute if the given value doesn't start with `http://` or `https://` by default. 
https://github.com/gitbucket/markedj/blob/5591594d17fec4365d7b008934d907e4052489ce/src/main/java/io/github/gitbucket/markedj/Options.java#L13-L34

You can customize the whitelist as follows:
```java
Options options = new Options();
options.getWhitelist().removeProtocols("img", "src", "http", "https");

String result = Marked.marked("![alt text](/img/some-image.png \"title\")", options);
// => <p><img src="/img/some-image.png" alt="alt text" title="title"></p>
```

**Comment by iku000888** [comment]
Thanks for the clarification!
I guess that was not really intuitive to me :sweat_drops: 
Perhaps some improvements on the readme? 
e.g. the explanation for option is "Whitelist of HTML tags."
which is hard to associate it with the allowed protocols in an `img` tag

Not sure how to articulate it best though.

**Comment by takezoe** [comment]
If I remember correctly, this is the default settings of Jsoup's whitelist with some modifications for GitBucket. Explaining on README makes sense!

**Comment by takezoe** [comment]
@iku000888 Does https://github.com/gitbucket/markedj/pull/23 work?

**Comment by iku000888** [comment]
Thank you, yes it does! @takezoe
