### ISSUE TITLE
Migrate notification extension to GitHub-like syntax

### ISSUE THREAD

**Issue by takezoe** [gitbucket/markedj#51]
Looks like GitHub now supports notification syntax. 
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

It might be better to migrate the notification extension we added in https://github.com/gitbucket/markedj/pull/45 to support it.

**Comment by takezoe** [comment]
cc: @thmarx

**Comment by thmarx** [comment]
Yes, I think this should be done. But gfm alerts seems to be extended blockquotes, so extension processing must move before processing of blockquotes.

I will look into this as soon I find some time. 

Maybe for inspiration: https://github.com/bent10/marked-extensions/tree/main/packages/alert

**Comment by thmarx** [comment]
@takezoe this issue can be closed

**Comment by takezoe** [comment]
Sure, thanks!
